# Generated by Django 4.2.4 on 2023-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('student_id', models.CharField(max_length=10, verbose_name='학번')),
                ('phone_num', models.CharField(max_length=13, verbose_name='전화번호')),
                ('score', models.IntegerField(verbose_name='점수')),
            ],
        ),
        migrations.CreateModel(
            name='QuizInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(verbose_name='퀴즈 번호')),
                ('category', models.CharField(choices=[('객관식', '객관식'), ('OX', 'OX'), ('주관식', '주관식')], default='주관식', max_length=10, verbose_name='카테고리')),
                ('answer', models.CharField(max_length=10, verbose_name='정답')),
                ('is_showed', models.BooleanField(default=False, verbose_name='사용자에게 보여줬는지')),
                ('sum_score', models.IntegerField(default=0, verbose_name='사용자 누적 점수')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(verbose_name='퀴즈 번호')),
                ('category', models.CharField(choices=[('객관식', '객관식'), ('OX', 'OX'), ('주관식', '주관식')], default='객관식', max_length=10, verbose_name='카테고리')),
                ('question', models.CharField(max_length=250, verbose_name='퀴즈')),
                ('answer_choices', models.CharField(choices=[('선택지1', '선택지1'), ('선택지2', '선택지2'), ('선택지3', '선택지3')], default='nothing', max_length=100, verbose_name='선택지')),
                ('is_showed', models.BooleanField(default=False, verbose_name='사용자에게 보여줬는지')),
                ('sum_score', models.IntegerField(default=0, verbose_name='사용자 누적 점수')),
            ],
        ),
    ]
