# Generated by Django 4.2.4 on 2023-08-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0, verbose_name='점수'),
        ),
    ]
