# Generated by Django 4.2.4 on 2023-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_participant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinput',
            name='category',
            field=models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='hard', max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='quizsimple',
            name='category',
            field=models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='normal', max_length=10, verbose_name='카테고리'),
        ),
    ]
