# Generated by Django 4.2.4 on 2023-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizinput_category_alter_quizsimple_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(verbose_name='퀴즈 번호')),
                ('category', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='easy', max_length=10, verbose_name='카테고리')),
                ('question', models.CharField(max_length=250, verbose_name='내용')),
                ('choices1', models.CharField(default='O', max_length=100, verbose_name='선택지1')),
                ('choices2', models.CharField(default='X', max_length=100, verbose_name='선택지2')),
                ('answer', models.CharField(max_length=100, verbose_name='정답')),
                ('sum_score', models.IntegerField(default=0, verbose_name='사용자 누적 점수')),
            ],
        ),
        migrations.CreateModel(
            name='QuizHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(verbose_name='퀴즈 번호')),
                ('category', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='hard', max_length=10, verbose_name='카테고리')),
                ('question', models.CharField(max_length=250, verbose_name='내용')),
                ('answer9_1', models.CharField(default='빅뱅', max_length=10, verbose_name='9변_1 정답')),
                ('answer9_2', models.CharField(default='빅뱅이론', max_length=10, verbose_name='9번_2 정답')),
                ('answer9_3', models.CharField(default='빅뱅 이론', max_length=10, verbose_name='9번_3 정답')),
                ('answer10_1', models.CharField(default='405', max_length=10, verbose_name='10번_1 정답')),
                ('answer10_2', models.CharField(default='405호', max_length=10, verbose_name='10번_2 정답')),
                ('sum_score', models.IntegerField(default=0, verbose_name='사용자 누적 점수')),
            ],
        ),
        migrations.CreateModel(
            name='QuizNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(verbose_name='퀴즈 번호')),
                ('category', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='normal', max_length=10, verbose_name='카테고리')),
                ('question', models.CharField(max_length=250, verbose_name='내용')),
                ('choices1', models.CharField(max_length=100, verbose_name='선택지1')),
                ('choices2', models.CharField(max_length=100, verbose_name='선택지2')),
                ('choices3', models.CharField(max_length=100, verbose_name='선택지3')),
                ('answer', models.CharField(max_length=100, verbose_name='정답')),
                ('sum_score', models.IntegerField(default=0, verbose_name='사용자 누적 점수')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizInput',
        ),
        migrations.DeleteModel(
            name='QuizSimple',
        ),
    ]
